version: "3.8"

services:
  redis_container:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  
  celery_worker:
    build: .
    command: celery -A app.workers.celery worker --loglevel=info
    depends_on:
      - redis_container
    environment:
      - CELERY_BROKER_URL=redis://redis_container:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_container:6379/0
