"""Add URLRecord model

Revision ID: b2970a65cfe9
Revises: 17e6b088e8c3
Create Date: 2025-02-09 13:10:15.925290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2970a65cfe9'
down_revision: Union[str, None] = '17e6b088e8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_records', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_records', 'created_at')
    # ### end Alembic commands ###
